"""delegation.py - security-owned on-behalf-of forwarding (keep this file under CODEOWNERS).

Lets a tool call a downstream Kerberized service as the user who called the MCP
server, so the downstream sees the real human rather than a shared service
account. The downstream is any Kerberized service the caller could reach: a CI
system, an internal REST API, a directory, a database proxy. The shipped example
(mcp_server.trigger_build) uses CI only because it is easy to picture; nothing
here is CI-specific. Tool developers do not edit this file; they add a tool to
mcp_server.py and, with security review, one line to TOOL_TARGETS below.

Mechanism: evidence-based S4U2Proxy constrained delegation. When the caller
authenticates, MIT composes a credential naming them, built from the ticket they
presented. We show that to the KDC and ask for a ticket to one named downstream
service. Three limits fall out:

  1. It cannot act for a user who never called. The caller's own ticket is the
     evidence, so there is nothing to present for someone who never showed up.
  2. It cannot reach a service TOOL_TARGETS has not named. Enforced here, by this
     file.
  3. It cannot be a full forwarded TGT. Enforced here too, by is_narrow_evidence()
     below, and that check is what keeps limit 1 and the KDC's own allowlist
     meaningful.

Why limit 3 exists. A caller who sets GSS_C_DELEG_FLAG hands us their whole TGT
rather than a narrow evidence credential. Accepting one would let the KDC issue a
ticket to anything that caller could reach, as them, through us: the realm's
servicedelegationtarget allowlist does not apply to a TGT. Demonstrated on a live
KDC against ldap@ipa, which no rule permits. We refuse it, and we can tell the two
apart reliably; see is_narrow_evidence() for the mechanism and for why a hostile
client cannot have it both ways. TOOL_TARGETS is therefore not the only control,
but it is the one a reviewer can read, so review it as if it were.

Not used, deliberately: S4U2Self / protocol transition (ok_to_auth_as_delegate).
That variant lets a service mint a ticket as any user without them ever
authenticating, which turns a keytab into an impersonation oracle. It is the
variant the security literature warns about; the recommended form is constrained
delegation without protocol transition, which is what this is.

Off by default. With MCP_DELEGATION unset, enabled() is False, no acceptor ever
requests an evidence credential, and every call here denies. Turning it on is a
deployment decision with a real cost, documented in ../SECURITY.md [D1].

Prerequisites (all outside this file, all verified against a live KDC):
  - the acceptor credential acquired with usage='both' (see spnego_auth.py)
  - a FreeIPA servicedelegationrule binding this service to a target list
  - the caller's ticket must be forwardable. Without protocol transition the KDC
    hard-requires it. A non-forwardable caller is refused with the same opaque
    KDC_ERR_BADOPTION as a missing rule, so see _explain() before diagnosing.
  - MIT krb5 >= 1.16 and a python-gssapi exposing raw.inquire_cred_by_oid, which
    is_narrow_evidence() needs. Without them it returns False and every forward is
    denied, deliberately; see its docstring.
"""
import os
import re

# tool name -> frozenset of allowed downstream SPNs, hostbased form 'svc@fqdn'.
# Deny by default: a tool absent from this map may not forward, and an empty map
# means the feature does nothing at all. Never populate this from a request, a
# tool argument, or config a tool author controls: a caller-chosen target is
# server-side request forgery carrying the caller's own identity.
#
# FQDNs only, never short names, so the target cannot be widened by a resolver.
TOOL_TARGETS = {
    # 'trigger_build': frozenset({'HTTP@ci.example.internal'}),
}

_SPN_RE = re.compile(r'^[A-Za-z0-9_-]{1,32}@[a-z0-9.-]{3,253}$')
_TOOL_RE = re.compile(r'^[a-z][a-z0-9_]{0,63}$')
_MAX_TARGETS_PER_TOOL = 8
_MAX_ENV_TARGETS = 16


def _targets_from_env(raw):
    """Parse the operator overlay: MCP_DELEGATION_TARGETS='tool=svc@fqdn,...'.

    Why it exists. A real target is a real hostname, and this repo ships without
    any, so the alternative is every deployment hand-editing a security-owned file
    and carrying that diff forever. This keeps the site's targets in site.env,
    next to MCP_DELEGATION itself, where the same operator already decides whether
    forwarding happens at all.

    Why it is not a hole. The threat this whole file exists to stop is a
    caller-chosen target. This value comes from the systemd unit's EnvironmentFile,
    which is root-owned; a caller cannot reach it, and neither can a tool author
    editing tool code. It is the same trust level as MCP_DELEGATION.

    It cannot override a literal row above. A reviewed target must not be silently
    redirected by a deployment, so a collision is fatal rather than resolved by
    precedence. Every parse failure raises at import, so a typo takes the service
    down instead of leaving it running with a policy nobody read."""
    out = {}
    for item in [x.strip() for x in (raw or '').split(',') if x.strip()]:
        tool, sep, spn = item.partition('=')
        tool, spn = tool.strip(), spn.strip()
        if not sep or not _TOOL_RE.match(tool):
            raise ValueError('MCP_DELEGATION_TARGETS: bad entry %r, want tool=svc@fqdn' % item)
        if not _SPN_RE.match(spn):
            raise ValueError('MCP_DELEGATION_TARGETS: bad SPN %r for tool %r' % (spn, tool))
        if tool in TOOL_TARGETS:
            raise ValueError('MCP_DELEGATION_TARGETS: %r is already set in code and a '
                             'deployment may not redirect a reviewed target' % tool)
        if tool in out:
            raise ValueError('MCP_DELEGATION_TARGETS: %r listed twice' % tool)
        out[tool] = frozenset({spn})
    if len(out) > _MAX_ENV_TARGETS:
        raise ValueError('MCP_DELEGATION_TARGETS: too many entries (%d)' % len(out))
    return out


# Merged once, at import, so the policy cannot change under a running process and
# a bad value is a startup failure rather than a per-request surprise.
TOOL_TARGETS.update(_targets_from_env(os.environ.get('MCP_DELEGATION_TARGETS')))


# MIT krb5 GSS_KRB5_GET_CRED_IMPERSONATOR (gssapi_krb5.h, MIT krb5 >= 1.16).
# Returns the impersonator principal for an S4U2Proxy evidence credential, and an
# empty set for anything else, a forwarded TGT included.
_IMPERSONATOR_OID_STR = '1.2.840.113554.1.2.2.5.14'
_IMPERSONATOR_OID = None


def is_narrow_evidence(cred, expect_impersonator):
    """True iff `cred` is an S4U2Proxy evidence credential naming
    `expect_impersonator` (this service, principal form 'HTTP/host@REALM').

    False for the caller's full forwarded TGT, false for our own initiator
    credential, and false whenever the answer cannot be established.

    Why a hostile client cannot defeat this, which is the part that matters. MIT
    sets cred->impersonator in exactly one place, kg_compose_deleg_cred(), on the
    accept path taken when the caller did not set GSS_C_DELEG_FLAG, and it sets it
    from the local acceptor credential's own name. Nothing off the wire reaches
    that field, so it cannot be forged. A caller who does set the flag routes MIT
    down krb5_rd_cred() instead, which never sets it. The client's single lever
    picks the branch, and the branch that would hand us the dangerous credential
    is the one that loses the marker, so they cannot have both. Measured on a live
    KDC over 200 iterations with distinct caller and service principals: no
    misclassification either way, ~0.1 ms, entirely in memory with no KDC round
    trip.

    Comparing against expect_impersonator rather than merely checking that the
    field is non-empty is what stops a credential composed by some other acceptor
    from passing here.

    Fails closed. An MIT krb5 older than 1.16, a python-gssapi without
    inquire_cred_by_oid, a non-MIT mech, or any error at all returns False, which
    denies forwarding rather than assuming the credential is narrow. On such a
    platform [D1] does not work; that is the intended outcome, because the
    alternative is forwarding credentials we cannot classify."""
    global _IMPERSONATOR_OID
    import gssapi
    from gssapi.exceptions import GSSError

    inquire = getattr(gssapi.raw, 'inquire_cred_by_oid', None)
    if inquire is None or cred is None or not expect_impersonator:
        return False
    if _IMPERSONATOR_OID is None:
        try:
            _IMPERSONATOR_OID = gssapi.OID.from_int_seq(_IMPERSONATOR_OID_STR)
        except Exception:
            return False
    try:
        bufs = inquire(cred, _IMPERSONATOR_OID)
    except GSSError:
        return False
    except Exception:
        return False
    if len(bufs) != 1:
        return False
    try:
        return bufs[0].decode('utf-8') == expect_impersonator
    except (UnicodeDecodeError, AttributeError):
        return False


class DelegationError(Exception):
    """Forwarding was refused. `reason` is a short slug for the audit log only;
    never send it to the caller, and never send the KDC's text either."""
    def __init__(self, reason):
        super().__init__(reason)
        self.reason = reason


def enabled():
    """True only when the operator has deliberately switched this on. Checked at
    every call rather than cached, so a misconfigured process cannot drift into
    forwarding after the fact."""
    return os.environ.get('MCP_DELEGATION', '').strip().lower() in ('1', 'true', 'yes', 'on')


def target_for(tool):
    """The single allowed downstream SPN for `tool`, or raise. Deny by default.

    Returns exactly one target. A tool with several configured is a configuration
    error rather than a runtime choice, because 'which one' would then have to be
    decided somewhere, and the only inputs available at that point come from the
    caller."""
    if not enabled():
        raise DelegationError('delegation-disabled')
    allowed = TOOL_TARGETS.get(tool)
    if not allowed:
        raise DelegationError('no-target-policy')
    if len(allowed) > _MAX_TARGETS_PER_TOOL:
        raise DelegationError('too-many-targets')
    if len(allowed) != 1:
        raise DelegationError('ambiguous-target')
    spn = next(iter(allowed))
    if not isinstance(spn, str) or not _SPN_RE.match(spn):
        raise DelegationError('invalid-target-spn')
    return spn


def negotiate_header(evidence_cred, tool, impersonator, audit=None):
    """Return an 'Authorization: Negotiate <b64>' value that authenticates to the
    tool's allowlisted downstream service as the caller.

    evidence_cred is what spnego_auth.authenticate(..., want_evidence=True)
    returned. Fails closed on every path: a disabled feature, an unlisted tool, a
    missing evidence credential and a KDC refusal all raise DelegationError, and
    none of them fall back to acting as the service itself. Acting as the service
    would silently defeat the entire point, which is that the downstream sees the
    real user, and it would do so while appearing to work."""
    import base64

    import gssapi
    from gssapi.exceptions import GSSError

    spn = target_for(tool)                       # raises unless explicitly allowed
    if evidence_cred is None:
        # Either delegation is off in the acceptor, or the caller's ticket could
        # not serve as evidence. Never substitute our own identity.
        raise DelegationError('no-evidence-credential')
    if not is_narrow_evidence(evidence_cred, impersonator):
        # The caller set GSS_C_DELEG_FLAG and handed us their whole TGT, or the
        # platform cannot classify the credential. Either way, using it would
        # reach targets the realm never approved, as them, through us. Our own
        # client never delegates ([CL1]), so in practice this is a modified one.
        raise DelegationError('credential-not-narrow-evidence')

    try:
        name = gssapi.Name(spn, gssapi.NameType.hostbased_service)
        ctx = gssapi.SecurityContext(name=name, creds=evidence_cred, usage='initiate')
        token = ctx.step()
    except GSSError as e:
        raise DelegationError(_explain(e))

    if not token:
        raise DelegationError('empty-token')
    if audit:
        # actor / subject / target, the three names an incident responder needs to
        # reconstruct who did what through whom.
        audit({'event': 'delegate', 'outcome': 'allow', 'tool': tool,
               'subject': str(getattr(evidence_cred, 'name', '')), 'target': spn,
               'evidence': 'narrow'})
    return 'Negotiate ' + base64.b64encode(token).decode()


def _explain(err):
    """Map a KDC failure to an audit slug. KDC_ERR_BADOPTION covers at least three
    distinct causes and the text does not distinguish them, so the slug names the
    ambiguity instead of guessing: the operator needs to check the rule, the
    target list, and whether the caller's ticket was forwardable."""
    text = str(err)
    if 'option' in text.lower():
        return 'kdc-badoption:check-rule-target-and-caller-forwardable'
    return 'kdc-refused'
